# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - turbohtml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_e35269fb30f64f48be205de1be5ec0a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_74b7f7471c094f419717c72a87ec9aa3 }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.AzureAppService_ContainerUsername_e35269fb30f64f48be205de1be5ec0a3 }}/turbo-html
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=tag
          type=sha
          type=sha,format=long
        flavor: |
          latest=true


    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .      
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'turbohtml'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77d882ab5c9443789bb4ef7fae193bdb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e35269fb30f64f48be205de1be5ec0a3 }}/turbo-html:sha-${{ github.sha }}'